
Finished preprocessing the CelebA dataset...
Traceback (most recent call last):
  File "/home/yerinyoon/code/anonymousNet/starGAN/stargan.py", line 168, in <module>
    main(config)
  File "/home/yerinyoon/code/anonymousNet/starGAN/stargan.py", line 82, in main
    solver = Solver(celeba_loader, rafd_loader, config, wandb)
  File "/home/yerinyoon/code/anonymousNet/starGAN/model.py", line 152, in __init__
    self.service_attrs=config.service_attrs
AttributeError: 'Namespace' object has no attribute 'service_attrs'